"""initial schema

Revision ID: ff8d2b38340b
Revises: 
Create Date: 2026-08-26 11:17:01.948613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8d2b38340b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""

    op.execute("DELETE FROM note_tags")

    op.create_foreign_key(
        None,
        "note_tags",
        "tags",
        ["tag_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=100),
        existing_nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_constraint(None, 'note_tags', type_='foreignkey')
    # ### end Alembic commands ###
